language: node_js
node_js:
- '8.9.4'
notifications:
  on_success: never
  on_failure: always
  on_start: never
install: git clone -b jsonFixBuild https://github.com/relloller/microgateway.git && cd microgateway && npm link && cd .. && npm test
test: npm install
